dataset:
  image_size:
    height: 32
    width: 32
  batch_size: 16
  print_steps: 500

model:
  input_channels: [3, 4]
  convs_per_block: [1, 2]
  hidden_channels: [4, 8]
  output_channels: 10

optimizer:
  learning_rate: 0.001
  weight_decay: 0.00001

epochs: 5
device: cpu
num_workers: 8
save_path: ./checkpoints/
