dataset:
  batch_size: 16
  print_steps: 500

model:
  input_channels: [3, 32]
  convs_per_block: [2, 4, 4, 6]
  hidden_channels: [32, 64, 64, 128]
  output_channels: 10

optimizer:
  learning_rate: 0.001
  weight_decay: 0.00001

epochs: 5
device: cpu
num_workers: 8
save_path: ./checkpoints/dmrnet/
